use API_Cultura

INSERT INTO Pertenece VALUES(16, 1)
INSERT INTO Pertenece VALUES(2, 1)
INSERT INTO Pertenece VALUES(21, 1)
INSERT INTO Pertenece VALUES(27, 1)

INSERT INTO Pertenece VALUES(7, 2)
INSERT INTO Pertenece VALUES(3, 2)
INSERT INTO Pertenece VALUES(24, 2)
INSERT INTO Pertenece VALUES(25, 2)

INSERT INTO Pertenece VALUES(10, 3)
INSERT INTO Pertenece VALUES(18, 3)
INSERT INTO Pertenece VALUES(23, 3)
INSERT INTO Pertenece VALUES(26, 3)


INSERT INTO Pertenece VALUES(17, 4)
INSERT INTO Pertenece VALUES(19, 4)
INSERT INTO Pertenece VALUES(13, 4)
INSERT INTO Pertenece VALUES(28, 4)