use API_Cultura

-- Primavera
INSERT INTO Pertenece VALUES(16, 1)
INSERT INTO Pertenece VALUES(2, 1)
INSERT INTO Pertenece VALUES(21, 1)
INSERT INTO Pertenece VALUES(27, 1)
INSERT INTO Pertenece VALUES(7, 1)
INSERT INTO Pertenece VALUES(8, 1)
INSERT INTO Pertenece VALUES(14, 1)

-- Verano
INSERT INTO Pertenece VALUES(3, 2)
INSERT INTO Pertenece VALUES(24, 2)
INSERT INTO Pertenece VALUES(25, 2)
INSERT INTO Pertenece VALUES(4, 2)
INSERT INTO Pertenece VALUES(9, 2)
INSERT INTO Pertenece VALUES(10, 2)
INSERT INTO Pertenece VALUES(11, 2)
INSERT INTO Pertenece VALUES(15, 2)
INSERT INTO Pertenece VALUES(18, 2)

-- Otono
INSERT INTO Pertenece VALUES(18, 3)
INSERT INTO Pertenece VALUES(23, 3)
INSERT INTO Pertenece VALUES(26, 3)
INSERT INTO Pertenece VALUES(5, 3)
INSERT INTO Pertenece VALUES(13, 3)
INSERT INTO Pertenece VALUES(19, 3)
INSERT INTO Pertenece VALUES(21, 3)
INSERT INTO Pertenece VALUES(24, 3)
INSERT INTO Pertenece VALUES(28, 3)

--Invierno
INSERT INTO Pertenece VALUES(17, 4)
INSERT INTO Pertenece VALUES(19, 4)
INSERT INTO Pertenece VALUES(13, 4)
INSERT INTO Pertenece VALUES(16, 4)
INSERT INTO Pertenece VALUES(7, 4)